[package]
name = "jetski"
version = "0.1.0"
authors = ["Martin Billinger <flkazemakase@gmail.com>"]
edition = "2018"

[dependencies]
llvm-sys = "80"
pest = "2.1"
pest_derive = "2.1"

[dev-dependencies]
rustyline = "4"
